all:
    children:
        site:
            hosts:
                server:
                    ansible_connection: ssh
                    ansible_user: ruslan
                    ansible_ssh_pass: Matera2846
                    ansible_sudo_pass: Matera2846
                    ansible_host: 212.32.242.38
                    ansible_port: 22
